name: Create JAR and list JARs

on:
  push:
    branches:
      - master

jobs:

  dockerize-and-upload:
    runs-on: ubuntu-22.04

    steps:

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: mvn -q -B package --file pom.xml -DskipTests

      - name: List the JARs - funcionará chan chan channnnnn
        run: ls target/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ci-ms-curso:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ci-ms-curso:latest
          file: ./dockerfile.prod
          context: .

  azure-deploy-image:
    needs: dockerize-and-upload
    runs-on: ubuntu-22.04
    
    steps:

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Replace variables
      run: |
        sed -i "/DATABASE_URL/c       \      - ${{ secrets.DATABASE_URL }}" ./docker-compose.test.yml
        sed -i "/DATABASE_USERNAME/c  \      - ${{ secrets.DATABASE_USERNAME }}" ./docker-compose.test.yml
        sed -i "/DATABASE_PASSWORD/c  \      - ${{ secrets.DATABASE_PASSWORD }}" ./docker-compose.test.yml

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ms-curso-ci
        images: ${{ secrets.DOCKERHUB_USERNAME }}/ci-ms-curso:latest
        configuration-file: ./docker-compose.test.yml

