name: Create JAR and list JARs

on:
  push:
    branches:
      - main

jobs:
  create-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create the JAR
        run: ./mvnw clean package -DskipTests

      - name: List the JARs - funcionará chan chan channnnnn
        run: ls target/