name: Create JAR and list JARs

on:
  push:
    branches:
      - master

jobs:

  create-jar:
    runs-on: ubuntu-22.04

    steps:

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: mvn -q -B package --file pom.xml

      - name: List the JARs - funcionará chan chan channnnnn
        run: ls target/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ms-curso
          path: target/ms-curso-*.jar
          if-no-files-found: error
          overwrite: true
          retention-days: 1

  # docker-build-and-push:
  #   runs-on: ubuntu-22.04
  #   needs: create-jar

  #   steps:

  #     - name: Check out the repository
  #       uses: actions/checkout@v3

  #     - name: Package the JAR
  #       run: mvn package -DskipTests
